# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sql-face',
                'doc_host': 'https://AndreaMacarulla.github.io',
                'git_url': 'https://github.com/AndreaMacarulla/sql-face',
                'lib_path': 'sql_face'},
  'syms': {'sql_face.core': {'sql_face.core.foo': ('core.html#foo', 'sql_face/core.py')}}}