# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['home', 'input_dir', 'foo']

# %% ../nbs/00_core.ipynb 3
def foo(
    x:int # number to compute
    ) -> int:
    return x + 2

"Add 2 to integer number"

import os
home = os.path.expanduser("~")
input_dir = os.path.join(home, 'lr_video_project', 'image_datasets')
