# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_databases.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/04_databases.ipynb 3
#TODO: add databases module

# DATABASES = {'lfw': LFW 
#                     # 'xqlfw': XQLFW, 
#                     #  'scface': SCFace, 
#                     #  'forenface': ForenFace, 
#                     #  'utkface': UTKFace,
#                     #  'enfsi': Enfsi, 
#                     #  'enfsi2015': Enfsi2015
#                      }


